FROM golang:1.19

RUN apt-get update
RUN apt-get install -y npm shellcheck chromium

ENV GO111MODULE=on
RUN go install golang.org/x/tools/cmd/goimports
RUN go install mvdan.cc/sh/v3/cmd/shfmt
RUN go install golang.org/x/tools/cmd/stringer
RUN go install golang.org/x/lint/golint
RUN go install github.com/agnivade/wasmbrowsertest

RUN npm --unsafe-perm=true install -g prettier
RUN npm --unsafe-perm=true install -g netlify-cli
